core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('post.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    

post/urls.py
from django.urls import path
from .views import (
    PostListView,
    # PostDeleteView,
    # AboutView,
    # PostDetailView,
    # CreatePostView,
    # PostUpdateView,
    # DraftListView,
    # PostDeleteView,
    # post_publish,
    # add_comment_to_post,
    # comment_approve,
    # comment_remove,
    # CategoryView,
    )

# from django.contrib.sitemaps.views import sitemap
# from .sitemaps import PostSitemap
# from .feeds import LatestPostsFeed

app_name = 'post'
urlpatterns = [
    path(
        '', PostListView.as_view(),
        name='home'),
    # path(
    #     'about', AboutView.as_view(),
    #     name='about'),
    # path(
    #     'cat/', CategoryView.as_view(),
    #     name='cat'),
    # path(
    #     'post/<pk>', PostDetailView.as_view(),
    #     name='post_detail'),
    # path(
    #     'post/', CreatePostView.as_view(),
    #     name='post_new'),
    # path(
    #     'post/<pk>/edit/', PostUpdateView.as_view(),
    #     name='post_edit'),
    # path(
    #     'drafts/', DraftListView.as_view(),
    #     name='post_draft_list'),
    # path(
    #     'post/<pk>/remove/', PostDeleteView.as_view(),
    #     name='post_remove'),
    # path(
    #     'post/<pk>/publish/', post_publish,  name='post_publish'),
    # path(
    #     'post/<pk>/comment/', add_comment_to_post,
    #     name='add_comment_to_post'),
    # path(
    #     'comment/<pk>/approve/', comment_approve,
    #     name='comment_approve'),
    # path(
    #     'comment/<pk>/remove/', comment_remove,
    #     name='comment_remove'),
]

# sitemaps = {
#     "posts": PostSitemap
# }

# urlpatterns += [
#     path("sitemap.xml", sitemap, {'sitemaps': sitemaps}, name='sitemap')
# ]


# urlpatterns += [
#     path("feed/rss", LatestPostsFeed(), name='post_feed')
# ]

comment/models.py
from django.db import models
from post.models import Post
# Create your models here.


class Comment(models.Model):
    post = models.ForeignKey(
        Post, related_name='comments',
        on_delete=models.CASCADE
        )
    author = models.CharField(max_length=200)
    visitor = models.CharField(max_length=300, blank=True)
    email = models.EmailField()
    message = models.TextField()
    created_date = models.DateTimeField(
        auto_now_add=True
        )
    approve_comment = models.BooleanField(
        default=False
        )

    def approve(self):
        self.approve_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

post/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
# from django.conf import settings
User = get_user_model()


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Favorite(models.Model):
    user_profile = models.ForeignKey(
        UserProfile, related_name='favorites', on_delete=models.CASCADE)
    likes = models.ManyToManyField('Category')
    others = models.CharField(
        max_length=400, default="separate with a comma i.e ',' ")

    def __str__(self):
        return self.user_profile


class Socials(models.Model):
    user_profile = models.ForeignKey(
        UserProfile, related_name='socials', on_delete=models.CASCADE)
    social_name = models.CharField(max_length=200)
    profile_url = models.URLField()

    def __str__(self):
        return self.profile_url

    class Meta:
        verbose_name_plural = 'Socials'


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    date_published = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to='post/pic/')

    def publish_post(self):
        self.date_published = timezone.now()
        # self.updated_on = timezone.now()
        self.published = True
        self.save()

    def approved_comments(self):
        return self.comments.filter(approve_comment=True)

    def comments_count(self):
        return self.comments.filter(approve_comment=True).count()

    # def popular_posts(self):
    #     return self.filter(published=True).order_by('-views')[:5]

    def related_posts(self):
        return self.categories.all_posts()

    def published_posts(self):
        return self.filter(published=True)

    def drafts(self):
        return self.filter(published=False)

    # def get_absolute_url(self):
    #     return reverse("post_detail", kwargs={'pk': self.pk})

    # def get_update_url(self):
    #     return reverse("post_detail", kwargs={'pk': self.pk})

    # def get_remove_url(self):
    #     return reverse("post_detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']

    # def save(self, *args, **kwargs):
        # super(Post, self).save(*args, **kwargs)
        # self.instance.author = get_user(request)
        # self.published_date = timezone.now()
        # self.updated_on = timezone.now()
        # self.save()

        # return super(Post, self).save(*args, **kwargs)


class Category(models.Model):
    post_for = models.ManyToManyField(Post, related_name='categories')
    category_name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'Categories'

    def all_posts(self):
        return self.post_for.all()

    def __str__(self):
        return self.category_name


def create_profile(sender, instance, created, *args, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_profile, sender=User)

comment/views.py
from django.shortcuts import render

# Create your views here.

post/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from django.utils import timezone
from post.models import (
    Post,
    Category,
)
# Create your views here.


# class CategoryView(View):
#     template_name = 'post/home.html'

#     def get(self, request, *args, **kwargs):
#         catg = Category.objects.all()
#         pop = Post.objects.filter(published=True).order_by('-views')
#         context = {
#             'cat': catg,
#             'pop': pops
#         }
#         return render(request, self.template_name, context)


class PostListView(ListView):
    template_name = 'post/home.html'
    context_object_name = 'postlist'
    paginate_by = 5
    queryset = Post.objects.filter(
            date_published__lte=timezone.now(), published=True
            ).order_by('-date_published')

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        catg = Category.objects.all()
        pop = Post.objects.filter(published=True).order_by('-views')
        context = {
            'cat': catg,
            'pops': pop
        }
        return context
    

templates/_scripts.html
{% load static %}

<script src="{% static "js/vendor/jquery-2.2.4.min.js" %}"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"crossorigin="anonymous"></script> -->
<script src="{% static "js/vendor/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static "js/easing.min.js" %}"></script>
<script src="{% static "js/hoverIntent.js" %}"></script>
<script src="{% static "js/superfish.min.js" %}"></script>
<script src="{% static "js/jquery.ajaxchimp.min.js" %}"></script>
<script src="{% static "js/jquery.magnific-popup.min.js" %}"></script>
<script src="{% static "js/owl.carousel.min.js" %} "></script>
<script src="{% static "js/owl-carousel-thumb.min.js" %}"></script>
<script src="{% static "js/jquery.sticky.js" %}"></script>
<script src="{% static "js/jquery.nice-select.min.js" %}"></script>
<script src="{% static "js/parallax.min.js" %}"></script>
<script src="{% static "js/waypoints.min.js" %}"></script>
<script src="{% static "js/wow.min.js" %}"></script>
<script src="{% static "js/jquery.counterup.min.js" %} "></script>
<script src="{% static "js/mail-script.js" %}"></script>
<script src="{% static "js/main.js" %}"></script>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="codepixer">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Blog</title>

	<!--
			Google Font
			============================================= -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:300,500,600" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500i" rel="stylesheet">

	<!--
			CSS
			============================================= -->
	<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/themify-icons/0.1.2/css/themify-icons.css"> -->
	<link rel="stylesheet" href="{% static "css/linearicons.css" %}">
	<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
	<link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
	<link rel="stylesheet" href="{% static "css/nice-select.css" %}">
	<link rel="stylesheet" href="{% static "css/animate.min.css" %}">
	<link rel="stylesheet" href="{% static "css/owl.carousel.css" %}">
	<link rel="stylesheet" href="{% static "css/main.css" %}">
</head>

<body>

	<!-- Start Header Area -->
	<header id="header">
		<div class="container">
			<div class="row align-items-center justify-content-between d-flex">
				<div id="logo">
					<a href="index.html"><img src=" {% static "img/logo.png" %} " alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li><a href="index.html">Home</a></li>
						<li><a href="about.html">About</a></li>
						<li><a href="courses.html">Courses</a></li>
						<li class="menu-has-children"><a href="">Pages</a>
							<ul>
								<li><a href="elements.html">Elements</a></li>
							</ul>
						</li>
						<li class="menu-has-children menu-active"><a href="">Blog</a>
							<ul>
								<li><a href="blog-home.html">Blog Home</a></li>
								<li><a href="blog-single.html">Blog Details</a></li>
							</ul>
						</li>
						<li><a href="contact.html">Contact</a></li>
					</ul>
				</nav><!-- #nav-menu-container -->
			</div>
		</div>
	</header>
	<!-- End Header Area -->


	<!-- Start Banner Area -->
	<section class="banner-area relative">
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">
						Blog Home
					</h1>
					<p>In the history of modern astronomy, there is probably no one greater leap forward than the building and launch of
						the space telescope.</p>
					<div class="link-nav">
						<span class="box">
							<a href="index.html">Home </a>
							<i class="lnr lnr-arrow-right"></i>
							<a href="{% url 'post:home' %}">Blog</a>
						</span>
					</div>
				</div>
			</div>
		</div>
		<div class="rocket-img">
			<img src="img/rocket.png" alt="">
		</div>
	</section>
	<!-- End Banner Area -->

	<!-- Start top-category-widget Area -->
	<section class="top-category-widget-area pt-90 pb-90 ">
		<div class="container">
			<div class="row">
				<div class="col-lg-4">
					<div class="single-cat-widget">
						<div class="content relative">
							<div class="overlay overlay-bg"></div>
							<a href="#" target="_blank">
								<div class="thumb">
									<img class="content-image img-fluid d-block mx-auto" src="img/blog/cat-widget1.jpg" alt="">
								</div>
								<div class="content-details">
									<h4 class="content-title mx-auto text-uppercase">Social life</h4>
									<span></span>
									<p>Enjoy your social life together</p>
								</div>
							</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="single-cat-widget">
						<div class="content relative">
							<div class="overlay overlay-bg"></div>
							<a href="#" target="_blank">
								<div class="thumb">
									<img class="content-image img-fluid d-block mx-auto" src="img/blog/cat-widget2.jpg" alt="">
								</div>
								<div class="content-details">
									<h4 class="content-title mx-auto text-uppercase">Politics</h4>
									<span></span>
									<p>Be a part of politics</p>
								</div>
							</a>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="single-cat-widget">
						<div class="content relative">
							<div class="overlay overlay-bg"></div>
							<a href="#" target="_blank">
								<div class="thumb">
									<img class="content-image img-fluid d-block mx-auto" src="img/blog/cat-widget3.jpg" alt="">
								</div>
								<div class="content-details">
									<h4 class="content-title mx-auto text-uppercase">Food</h4>
									<span></span>
									<p>Let the food be finished</p>
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End top-category-widget Area -->

	<!-- Start post-content Area -->
	<section class="post-content-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 posts-list">
<!-- post -->

{% block allposts %}
    
{% endblock allposts %}
    
<!-- /post -->

        			<nav class="blog-pagination justify-content-center d-flex">
						
                        <ul class="pagination">
							<li class="page-item">
								<a href="#" class="page-link" aria-label="Previous">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-left"></span>
									</span>
								</a>
							</li>
							<li class="page-item"><a href="#" class="page-link">01</a></li>
							<li class="page-item active"><a href="#" class="page-link">02</a></li>
							<li class="page-item"><a href="#" class="page-link">03</a></li>
							<li class="page-item"><a href="#" class="page-link">04</a></li>
							<li class="page-item"><a href="#" class="page-link">09</a></li>
							<li class="page-item">
								<a href="#" class="page-link" aria-label="Next">
									<span aria-hidden="true">
										<span class="lnr lnr-chevron-right"></span>
									</span>
								</a>
							</li>
						</ul>
					</nav>
				</div>

				<div class="col-lg-4 sidebar-widgets">
					<div class="widget-wrap">
						
                        <div class="single-sidebar-widget search-widget">
							<form class="search-form" action="#">
								<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
								<button type="submit"><i class="fa fa-search"></i></button>
							</form>
						</div>


{% block userprofile %}
    
{% endblock userprofile %}
    
						
                        <div class="single-sidebar-widget popular-post-widget">
							<h4 class="popular-title">Popular Posts</h4>
							<div class="popular-post-list">

<!-- popular -->

{% block popular %}
    
{% endblock popular %}
    
<!-- popular -->
							
                            </div>
						</div>

                        <!-- ads -->
						<div class="single-sidebar-widget ads-widget">
							<a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
						</div>
                        <!-- /ads -->

						<div class="single-sidebar-widget post-category-widget">
							<h4 class="category-title">Post Catgories</h4>

{% block ca %}
	
{% endblock ca %}
							<!-- <ul class="cat-list">
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Technology</p>
										<p>37</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Lifestyle</p>
										<p>24</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Fashion</p>
										<p>59</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Art</p>
										<p>29</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Food</p>
										<p>15</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Architecture</p>
										<p>09</p>
									</a>
								</li>
								<li>
									<a href="#" class="d-flex justify-content-between">
										<p>Adventure</p>
										<p>44</p>
									</a>
								</li>
							</ul> -->
						</div>
						<div class="single-sidebar-widget newsletter-widget">
							<h4 class="newsletter-title">Newsletter</h4>
							<p>
								Here, I focus on a range of items and features that we use in life without giving them a second thought.
							</p>
							<div class="form-group d-flex flex-row">
								<div class="col-autos">
									<div class="input-group">
										<div class="input-group-prepend">
											<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
											</div>
										</div>
										<input type="text" class="form-control" id="inlineFormInputGroup" placeholder="Enter email" onfocus="this.placeholder = ''"
										 onblur="this.placeholder = 'Enter email'">
									</div>
								</div>
								<a href="#" class="bbtns">Subcribe</a>
							</div>
							<p class="text-bottom">
								You can unsubscribe at any time
							</p>
						</div>


{% block tags %}
    
{% endblock tags %}
    

					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End post-content Area -->

	<!-- Start Footer Area -->
	<footer class="footer-area section-gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-2 col-md-6 single-footer-widget">
					<h4>Top Products</h4>
					<ul>
						<li><a href="#">Managed Website</a></li>
						<li><a href="#">Manage Reputation</a></li>
						<li><a href="#">Power Tools</a></li>
						<li><a href="#">Marketing Service</a></li>
					</ul>
				</div>
				<div class="col-lg-2 col-md-6 single-footer-widget">
					<h4>Quick Links</h4>
					<ul>
						<li><a href="#">Jobs</a></li>
						<li><a href="#">Brand Assets</a></li>
						<li><a href="#">Investor Relations</a></li>
						<li><a href="#">Terms of Service</a></li>
					</ul>
				</div>
				<div class="col-lg-2 col-md-6 single-footer-widget">
					<h4>Features</h4>
					<ul>
						<li><a href="#">Jobs</a></li>
						<li><a href="#">Brand Assets</a></li>
						<li><a href="#">Investor Relations</a></li>
						<li><a href="#">Terms of Service</a></li>
					</ul>
				</div>
				<div class="col-lg-2 col-md-6 single-footer-widget">
					<h4>Resources</h4>
					<ul>
						<li><a href="#">Guides</a></li>
						<li><a href="#">Research</a></li>
						<li><a href="#">Experts</a></li>
						<li><a href="#">Agencies</a></li>
					</ul>
				</div>
				<div class="col-lg-4 col-md-6 single-footer-widget">
					<h4>Newsletter</h4>
					<p>You can trust us. we only send promo offers,</p>
					<div class="form-wrap" id="mc_embed_signup">
						<form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
						 method="get" class="form-inline">
							<input class="form-control" name="EMAIL" placeholder="Your Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Email Address '"
							 required="" type="email">
							<button class="click-btn btn btn-default"><span class="lnr lnr-arrow-right"></span></button>
							<div style="position: absolute; left: -5000px;">
								<input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
							</div>

							<div class="info"></div>
						</form>
					</div>
				</div>
			</div>
			<div class="footer-bottom row align-items-center">
				<p class="footer-text m-0 col-lg-8 col-md-12"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
				<div class="col-lg-4 col-md-12 footer-social">
					<a href="#"><i class="fa fa-facebook"></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-dribbble"></i></a>
					<a href="#"><i class="fa fa-behance"></i></a>
				</div>
			</div>
		</div>
	</footer>
	<!-- End Footer Area -->

	<!-- ####################### Start Scroll to Top Area ####################### -->
	<div id="back-top">
		<a title="Go to Top" href="#"></a>
	</div>
	<!-- ####################### End Scroll to Top Area ####################### -->

{% include '_scripts.html' %}
</body>

</html>

templates/post/_category.html
<ul class="cat-list">
    {% for c in cat %}
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>{{ c.category_name }} </p>
            <p>{{ c.all_posts.count }}</p>
            <ul>
            
            {% for post in c.all_posts %}
                <li><a href="">{{ post.title }}</a></li>
            {% endfor %}
                
            </ul>
        </a>
    </li>
    {% endfor %}
    
    <!-- <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Lifestyle</p>
            <p>24</p>
        </a>
    </li>
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Fashion</p>
            <p>59</p>
        </a>
    </li>
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Art</p>
            <p>29</p>
        </a>
    </li>
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Food</p>
            <p>15</p>
        </a>
    </li>
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Architecture</p>
            <p>09</p>
        </a>
    </li>
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>Adventure</p>
            <p>44</p>
        </a>
    </li> -->
</ul>

templates/post/home.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block allposts %}

{% for post in postlist %}
<div class="single-post row">
    <div class="col-lg-3  col-md-3 meta-details">
        <ul class="tags">
        
        {% for category in post.categories.all %}
            <li><a href="#">{{ category.category_name|title }},</a></li>
        {% endfor %}
            <!-- <li><a href="#">Technology,</a></li>
            <li><a href="#">Politics,</a></li>
            <li><a href="#">Lifestyle</a></li> -->

        </ul>
        <div class="user-details row">
            <p class="user-name col-lg-12 col-md-12 col-6"><a href="#">{{ post.author.username|title }}</a> <span class="lnr lnr-user"></span></p>
            <p class="date col-lg-12 col-md-12 col-6"><a href="#">{{ post.date_published|naturalday|title }}</a> <span class="lnr lnr-calendar-full"></span></p>
            <p class="view col-lg-12 col-md-12 col-6"><a href="#">{{ post.views|intword }} Views</a> <span class="lnr lnr-eye"></span></p>
            <p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{ post.comments_count|apnumber }} Comments</a> <span class="lnr lnr-bubble"></span></p>
        </div>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="feature-img">
            <img class="img-fluid" src="{{ post.image.url }}" alt="">
        </div>
        <a class="posts-title" href=""><h3>{{ post.title|title }}</h3></a>
        <p class="excert">
        {{ post.text |truncatechars:300|title }}
        </p>
        <a href="" class="primary-btn">View More</a>
    </div>
</div>    
{% endfor %}

{% endblock allposts %}
    

{% block userprofile %}
<div class="single-sidebar-widget user-info-widget">
    <img src="{% static 'img/blog/user-info.png' %}" alt="">
    <a href="#"><h4>Charlie Barber</h4></a>
    <p>
        Senior blog writer
    </p>
    <ul class="social-links">
        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
        <li><a href="#"><i class="fa fa-github"></i></a></li>
        <li><a href="#"><i class="fa fa-behance"></i></a></li>
    </ul>
    <p>
        Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot
        camp when you can get. Boot camps have itssuppor ters andits detractors.
    </p>
</div>
{% endblock userprofile %}


{% block popular %}

{% for pop in pops %}
<div class="single-post-list d-flex flex-row align-items-center">
    <div class="thumb">
        <img class="img-fluid" src="{{ pop.image.url }}" alt="">
    </div>
    <div class="details">
        <a href=""><h6>{{ pop.title }}</h6></a>
        <p>{{ pop.published_date }}</p>
    </div>
</div>
{% endfor %}


{% endblock popular %}

{% block ca %}
<ul class="cat-list">
    {% for c in cat %}
    <li>
        <a href="#" class="d-flex justify-content-between">
            <p>{{ c.category_name|title }} </p>
            <p>{{ c.all_posts.count }}</p>
            <ul>
            
            {% for post in c.all_posts %}
                <li><a href="">{{ post.title|title }}</a></li>
            {% endfor %}
                
            </ul>
        </a>
    </li>
    {% endfor %}
    
</ul>

{% endblock ca %}
    
{% block tags %}
<div class="single-sidebar-widget tag-cloud-widget">
    <h4 class="tagcloud-title">Tag Clouds</h4>
    <ul>
        <!-- {% for post in postlist %} -->
        {% for tag in cat %}
            <li><a href="#">{{ tag.category_name|title }}</a></li>
        {% endfor %}
        <!-- {% endfor %} -->
        
        <!-- <li><a href="#">Technology</a></li> -->
        <!-- <li><a href="#">Fashion</a></li>
        <li><a href="#">Architecture</a></li>
        <li><a href="#">Fashion</a></li>
        <li><a href="#">Food</a></li>
        <li><a href="#">Technology</a></li>
        <li><a href="#">Lifestyle</a></li>
        <li><a href="#">Art</a></li>
        <li><a href="#">Adventure</a></li>
        <li><a href="#">Food</a></li>
        <li><a href="#">Lifestyle</a></li>
        <li><a href="#">Adventure</a></li> -->
    </ul>
</div>
{% endblock tags %}

{% for post in postlist %}
{% for tag in post.categories.all %}
    <li><a href="#">{{ tag.category_name|title }}</a></li>
{% endfor %}
{% endfor %}